# spring:
#     datasource:
#         driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://localhost:3306/starwars?useTimezone=true&serverTimezone=UTC
#         username: root
#         password: admin123
#     jpa:
#         hibernate:
#             ddl-auto: update
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQL8Dialect
#         show-sql: false


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver


